### ISSUE TITLE
More descriptive commit message

### ISSUE THREAD

**Issue by superseb** [rancherlabs/updatecli-automation#5]
Example: https://github.com/rancher/rancher/pull/39694

Commit messages:

```
[chore: changed lines [12] of file "/tmp/updatecli/github/rancher/ranc…]
[chore: changed lines [12] of file "/tmp/updatecli/github/rancher/ranc…]
```

We should be able to use source/target description in the commit as the current commit messages don't help in identifying what functionally changed.

**Comment by macedogm** [comment]
We can customize it by using the `commitmessage` object in the `github` SCM. See docs https://www.updatecli.io/docs/plugins/scm/github/. That can achieve the desired effect, but the commit message will be the same for all PRs linked to the `targets` using the same `scmid`.

I also opened two issues upstream - https://github.com/updatecli/updatecli/issues/1004 and https://github.com/updatecli/updatecli/issues/1005 - and a PR - https://github.com/updatecli/updatecli/issues/1006 - with some improvements regarding the commit message.
